@startuml
left to right direction

skinparam backgroundColor white
skinparam shadowing true
skinparam roundcorner 30
skinparam linetype ortho
skinparam DefaultFontName Arial
skinparam DefaultFontSize 16

skinparam rectangle {
  BackgroundColor #FFF3E0-#FFE0B2
  BorderColor #FB8C00
  RoundCorner 20
}

rectangle "main.py\n(entrypoint)" as main
rectangle "cli.py\n(interface)" as cli
rectangle "client.py\n(TFTPClient)" as client
rectangle "tftp_packets.py\n(pacotes)" as packets
rectangle "exceptions.py" as exceptions
rectangle "logger.py" as logger
rectangle "Servidor TFTP" as server

main --> cli
cli --> client
client --> packets
client --> exceptions
client --> logger
cli --> logger

client --> server : UDP

@enduml